### ISSUE TITLE
src/rdrand-gen.c: 2 * novice error with EOF

### ISSUE THREAD

**Issue by dcb314** [BroukPytlik/RdRand#6]
[src/rdrand-gen.c:785]: (warning) Storing getc() return value in char variable and then comparing with EOF.

[src/rdrand-gen.c:808]: (warning) Storing getc() return value in char variable and then comparing with EOF.

Suggest use int, not char, for variable c.

**Comment by BroukPytlik** [comment]
Fixed in 2.1.0
